### ISSUE TITLE
Support for Ice 3.6.5 on Windows

### ISSUE THREAD

**Issue by manics** [conda-forge/zeroc-ice-feedstock#3]
Thanks for adding Ice to conda-forge. We [(OME)](https://github.com/ome/) also have our own [zeroc-ice36 conda package](https://anaconda.org/ome/zeroc-ice36-python) but we'd like to switch to using this package.

At the moment we're missing Windows support, which has been frequently requested by our users. Back in November 2019 I opened a [`conda-forge/staged-recipes` PR to add zeroc=ice 3.6.5](https://github.com/conda-forge/staged-recipes/pull/10324). As you can see from that PR windows builds were working but OS X wasn't.

The diff between the ci directories such as `.azure-pipelines`, `.ci_support` in https://github.com/conda-forge/staged-recipes/pull/10324 and this repo is quite large, so I can't see what's needed to add Windows support here. Would you be able to provide some help? Thanks!

**Comment by manics** [comment]
Hi @dpryan79

We've had a request from @tlambert03 who would like to package a plugin they're developing in conda-forge: https://github.com/tlambert03/napari-omero/pull/19#issuecomment-652374174

The plugin is for [Napari which is already in conda-forge](https://github.com/conda-forge/napari-feedstock), but it requires omero-py which isn't in conda-forge as it depends on zeroc-ice python, version 3.6. Could I have your thoughts on whether the zeroc-ice conda package could be updated to support Windows, and on the addition of an Ice 3.6 branch? Thanks!

@joshmoore

**Comment by dpryan79** [comment]
@manics Presumably it could be, can you make a PR to attempt the build on Windows? I think there were some errors when I tried that last.

**Comment by joshmoore** [comment]
@manics: anything outstanding here?

**Comment by manics** [comment]
No, this should've been auto-closed by https://github.com/conda-forge/zeroc-ice-feedstock/pull/6
